"""more indexes

Revision ID: 29c14f847280
Revises: f4a4b5118d20
Create Date: 2018-08-21 14:20:15.326684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c14f847280'
down_revision = 'f4a4b5118d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_accname'), 'accounts', ['accname'], unique=False)
    op.create_index(op.f('ix_categories_catname'), 'categories', ['catname'], unique=False)
    op.create_index(op.f('ix_categories_cattype'), 'categories', ['cattype'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_categories_cattype'), table_name='categories')
    op.drop_index(op.f('ix_categories_catname'), table_name='categories')
    op.drop_index(op.f('ix_accounts_accname'), table_name='accounts')
    # ### end Alembic commands ###
