services:
  db:
    env_file:
      - .env_prod_db
    restart: always

  web:
    env_file:
      - .env_prod_web
    command: gunicorn wsgi:app --disable-redirect-access-to-syslog --error-logfile '-' --access-logfile '-' --access-logformat '%(t)s [GUNICORN] %(h)s %(l)s %(u)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"' --workers 3 --bind '[::]:8000'
    volumes:
      - /opt/btt/static:/btt/webserver/static/
    restart: always

