services:
  db:
    image: postgres:11
    user: ${USERID}:${GROUPID}
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: gregcowell/btt:latest
    user: ${USERID}:${GROUPID}
    networks:
      - net
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - db

volumes:
  db:

networks:
  net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd01::/64
          gateway: fd01::1
