"""initial migration

Revision ID: 59ab8d3aae7b
Revises: 
Create Date: 2017-05-04 13:05:26.920104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ab8d3aae7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('accno', sa.Integer(), nullable=False),
    sa.Column('accname', sa.String(length=250), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('accno')
    )
    op.create_table('businesses',
    sa.Column('busno', sa.Integer(), nullable=False),
    sa.Column('busname', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('busno')
    )
    op.create_table('categories',
    sa.Column('catno', sa.Integer(), nullable=False),
    sa.Column('catname', sa.String(length=250), nullable=False),
    sa.Column('cattype', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('catno')
    )
    op.create_table('transactions',
    sa.Column('transno', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('busno', sa.Integer(), nullable=False),
    sa.Column('catno', sa.Integer(), nullable=False),
    sa.Column('accno', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['accno'], ['accounts.accno'], ),
    sa.ForeignKeyConstraint(['busno'], ['businesses.busno'], ),
    sa.ForeignKeyConstraint(['catno'], ['categories.catno'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('transno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('categories')
    op.drop_table('businesses')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
