"""remove name field

Revision ID: 6ff1fdc328a5
Revises: 29c14f847280
Create Date: 2018-08-26 15:16:22.316703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff1fdc328a5'
down_revision = '29c14f847280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
