"""Initial migration

Revision ID: ba6c8bbb13fc
Revises: 
Create Date: 2017-05-31 13:55:43.446909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6c8bbb13fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('accno', sa.Integer(), nullable=False),
    sa.Column('accname', sa.String(length=250), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('accno')
    )
    op.create_table('businesses',
    sa.Column('busno', sa.Integer(), nullable=False),
    sa.Column('busname', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('busno')
    )
    op.create_table('categories',
    sa.Column('catno', sa.Integer(), nullable=False),
    sa.Column('catname', sa.String(length=250), nullable=False),
    sa.Column('cattype', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('catno')
    )
    op.create_table('transactions',
    sa.Column('transno', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('busno', sa.Integer(), nullable=False),
    sa.Column('catno', sa.Integer(), nullable=False),
    sa.Column('accno', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['accno'], ['accounts.accno'], ),
    sa.ForeignKeyConstraint(['busno'], ['businesses.busno'], ),
    sa.ForeignKeyConstraint(['catno'], ['categories.catno'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('transno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('categories')
    op.drop_table('businesses')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
