"""add groups

Revision ID: f2e13b567540
Revises: 6ff1fdc328a5
Create Date: 2018-08-28 13:37:47.945953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e13b567540'
down_revision = '6ff1fdc328a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'group_id')
    )
    op.add_column('accounts', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('accounts_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'groups', ['group_id'], ['group_id'])
    op.drop_column('accounts', 'id')
    op.add_column('categories', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('categories_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'groups', ['group_id'], ['group_id'])
    op.drop_column('categories', 'id')
    op.add_column('transactions', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'groups', ['group_id'], ['group_id'])
    op.drop_column('transactions', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_id_fkey', 'transactions', 'users', ['id'], ['id'])
    op.drop_column('transactions', 'group_id')
    op.add_column('categories', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_id_fkey', 'categories', 'users', ['id'], ['id'])
    op.drop_column('categories', 'group_id')
    op.add_column('accounts', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_id_fkey', 'accounts', 'users', ['id'], ['id'])
    op.drop_column('accounts', 'group_id')
    op.drop_table('memberships')
    op.drop_table('groups')
    # ### end Alembic commands ###
